spring:
 application:
   name: eurekaserver
 config:
    import: optional:configserver:http://localhost:8071/  
 
 eureka:
  client:
    register-with-eureka: false  # Disable self-registration since this is a server
    fetch-registry: false  # Disable registry fetch for the server itself
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Specify server's own URL if there are multiple instances

      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true 
server:
  port : 8761
  
              
